server:
  port: 8088

spring:
  application:
    name: audit-service
  config:
    import: "optional:configserver:http://localhost:8888"
  datasource:
    url: jdbc:postgresql://localhost:5432/db_audit
    username: swami
    password: swami
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

swamisuite:
  jwt:
    jwks-client:
      url: http://localhost:8081/.well-known/jwks.json
      refresh-interval-seconds: 600
  services:
    internal-token: dev-internal-token-change-me

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
