server:
  port: 8083

spring:
  application:
    name: catalog-service
  config:
    import: "optional:configserver:http://localhost:8888"
  datasource:
    url: jdbc:postgresql://localhost:5432/db_catalog
    username: swami
    password: swami
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

swamisuite:
  services:
    internal-token: dev-internal-token-change-me

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
